- id: enforce_named_loggers
  name: Enforce Named Loggers
  description: This hook ensures that loggers always have names, which is important for Datadog
  entry: enforce_named_loggers.py
  language: python
  files: *.py

