- id: enforce-named-loggers
  name: Enforce Named Loggers
  description: This hook ensures that loggers always have names, which is important for Datadog
  entry: enforce-named-loggers
  language: python
  types: [python]
